config/urls.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views
from django.core.urlresolvers import reverse_lazy
from django.views.generic import RedirectView

urlpatterns = [
    url(r'^$', RedirectView.as_view(url='/erp-accounts/'), name="home"), #TemplateView.as_view(template_name='pages/home.html'), name="home"),
    url(r'^about/$', TemplateView.as_view(template_name='pages/about.html'), name="about"),

    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, include(admin.site.urls)),

    # User management
    url(r'^users/', include("erp.users.urls", namespace="users")),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^erp-accounts/', include('erp_accounts.urls')),


    # Your stuff: custom urls includes go here


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception("Bad Request!")}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception("Permissin Denied")}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception("Page not Found")}),
        url(r'^500/$', default_views.server_error),
    ]

erp/erp_accounts/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url

urlpatterns = [
    # URL pattern for the UserListView
    url(r'^coaccounts/', include('erp.erp_accounts.coaccounts.urls')),

]

erp_accounts/journal/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import url, include
from .views import JournalCreate, JournalListView, JournalUpdate
from .api import JournalList, JournalAPI

from django.views.generic import TemplateView

api_urls = [
    url(
        r'^list/$',
        JournalList.as_view(),
        name='journal-list-create-api'
    ),
    url(
        r'^update/(?P<pk>[0-9]+)/$',
        JournalAPI.as_view(),
        name='journal-api'
    ),
]


urlpatterns = [
    url(
        r'^create/$',
        JournalCreate.as_view(),
        name="journal-create"
    ),

    url(
        r'^list/$',
        JournalListView.as_view(),
        name="journal-list"
    ),

    url(
        r'^update/(?P<pk>[0-9]+)/$',
        JournalUpdate.as_view(),
        name="journal-update"
    ),

    # only for testing
    url(
        regex=r'^test/$',
        view=TemplateView.as_view
        (template_name='journal/test.html'),
        name="test"
    ),
    url(
        r'^api/',
        include(api_urls)
    ),

]

erp_accounts/urls.py
# -*- coding: utf-8 -*-
from __future__ import absolute_import, unicode_literals

from django.conf.urls import include, url
from .views import DashboardView

urlpatterns = [
    # URL pattern for the UserListView
    url(
        regex=r'^$',
        view=DashboardView.as_view(),
        name='main_dashboard'
    ),
    url(
        r'^coaccounts/',
        include(
            'erp_accounts.coaccounts.urls',
            namespace="coaccounts")
    ),
    url(
        r'^journal/', include(
            'erp_accounts.journal.urls',
            namespace="journal")

    ),

]

erp/erp_accounts/coaccounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals, absolute_import

from django.contrib.auth.models import AbstractUser
from django.core.urlresolvers import reverse
from django.db import models
from django.utils.encoding import python_2_unicode_compatible
from django.utils.translation import ugettext_lazy as _


@python_2_unicode_compatible
class Company(models.Model):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = models.CharField(_("Name of the company"), blank=True, max_length=255)
    financial_year = models.CharField(_("Financial Year"), blank=True, max_length=255)
    country = models.CharField(_("Country Name"), blank=True, max_length=255)
    currency = models.CharField(_("Currency"), blank=True, max_length=255)
    state = models.CharField(_("State"), blank=True, max_length=255)
    city = models.CharField(_("City"), blank=True, max_length=255)
    pan_no = models.CharField(_("Pan no."), blank=True, max_length=255)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('company:detail', kwargs={'company_name': self.name})

erp/erp_accounts/coaccounts/forms.py
from django import forms
from erp_accounts.coaccounts.models import Company
# place form definition here


class UserForm(forms.ModelForm):
    class Meta:
        # Set this form to use the User model.
        model = Company

        # Constrain the UserForm to just these fields.
        # fields = ("first_name", "last_name")

erp_accounts/coaccounts/forms.py
from django import forms
from erp_accounts.coaccounts.models import Company
# place form definition here


class UserForm(forms.ModelForm):
    class Meta:
        # Set this form to use the User model.
        model = Company

        # Constrain the UserForm to just these fields.
        # fields = ("first_name", "last_name")

erp/erp_accounts/coaccounts/views.py
# Create your views here.
import json
import uuid

import hashlib

from django.http import Http404
from django.views.generic import TemplateView
from braces.views import LoginRequiredMixin
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View
from django.utils.decorators import method_decorator
from django.core.context_processors import csrf
from django.views.generic import View
from braces.views import StaffuserRequiredMixin
from django.shortcuts import render_to_response, HttpResponse
from django.http import Http404, HttpResponseRedirect
from django.template import RequestContext
from django.shortcuts import render
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from erp.erp_accounts.coaccounts.models import Company

class ReadCompanyInformation(LoginRequiredMixin, UpdateView):
    fields = ['name', ]

    # we already imported User in the view code above, remember?
    model = Company

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse("users:detail",
                       kwargs={"username": self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)

erp_accounts/coaccounts/apis/views.py
from rest_framework import generics
from django.shortcuts import get_object_or_404

from erp_accounts.coaccounts.apis.serializers import AccountGroupSerializer, LedgerSerializer, CompanySerializer, FiscalYearSerializer
from erp_accounts.coaccounts.models import AccountGroup, Ledger, Company, FiscalYear

class CreateCompany(generics.CreateAPIView):
    model = Company
    serializer_class = CompanySerializer


class CompanyInfo(generics.RetrieveUpdateDestroyAPIView):
    model = Company
    queryset = Company.objects.all()
    serializer_class = CompanySerializer
    def get_object(self):
        pk = int(self.kwargs.get('pk'))
        return get_object_or_404(self.queryset, pk=pk)

class FiscalYearList(generics.ListCreateAPIView):
    model = FiscalYear
    queryset = FiscalYear.objects.all()
    serializer_class = FiscalYearSerializer


class FiscalYearAPI(generics.RetrieveUpdateDestroyAPIView):
    model = FiscalYear
    serializer_class = FiscalYearSerializer
    queryset = FiscalYear.objects.all()

    def get_object(self):
        pk = int(self.kwargs.get('pk'))
        return get_object_or_404(self.queryset, pk=pk)



class AccountGroupList(generics.ListCreateAPIView):
    model = AccountGroup
    queryset = AccountGroup.objects.all()
    serializer_class = AccountGroupSerializer


class AccountGroupAPI(generics.RetrieveUpdateDestroyAPIView):
    model = AccountGroup
    serializer_class = AccountGroupSerializer
    queryset = AccountGroup.objects.all()

    def get_object(self):
        pk = int(self.kwargs.get('pk'))
        return get_object_or_404(self.queryset, pk=pk)


class LedgerList(generics.ListCreateAPIView):
    model = Ledger
    queryset = Ledger.objects.all()
    serializer_class = LedgerSerializer


class LedgerAPI(generics.RetrieveUpdateDestroyAPIView):
    model = Ledger
    serializer_class = LedgerSerializer
    queryset = Ledger.objects.all()

    def get_object(self):
        pk = int(self.kwargs.get('pk'))
        return get_object_or_404(self.queryset, pk=pk)

erp_accounts/coaccounts/views.py
# Create your views here.
# import json
# import uuid

# import hashlib

# from django.http import Http404
# from django.views.generic import TemplateView
# from braces.views import LoginRequiredMixin
# from django.views.decorators.csrf import csrf_exempt
from django.views.generic import View
from django.core.urlresolvers import reverse
# from django.utils.decorators import method_decorator
# from django.core.context_processors import csrf
# from django.views.generic import View
# from braces.views import StaffuserRequiredMixin
from django.shortcuts import render_to_response, HttpResponse, HttpResponseRedirect
# from django.http import Http404, HttpResponseRedirect
from django.template import RequestContext
# from django.shortcuts import render
from django.views.generic import DetailView, CreateView, ListView, RedirectView, UpdateView
import json
from .models import Company, AccountGroup, FiscalYear

from .fiscal_year_view import *
class ReadCompanyInformation(View):
    template_name = "coaccounts/company_form.html"

    def get_context(self):
        params = {}
        return params
    # send the user back to their own page after a successful update

    def get(self, request, *args, **kwargs):
        count = Company.objects.all().count()
        print(count)
        if count > 0:
            return HttpResponseRedirect(reverse("coaccounts:update_company"))
        return render_to_response(
            self.template_name,
            self.get_context(),
            context_instance=RequestContext(request)
        )


class AddAccountGroup(View):
    template_name = "coaccounts/add_account_group.html"

    def get_context(self):
        params = {}
        return params

    def get(self, request, *args, **kwargs):
        return render_to_response(
            self.template_name,
            self.get_context(),
            context_instance=RequestContext(request)
        )

class AddAccountLedger(View):
    template_name = "coaccounts/add_account_ledger.html"

    # send the user back to their own page after a successful update
    def get(self, request, *args, **kwargs):
        return render_to_response(
            self.template_name,
            {},
            context_instance=RequestContext(request)
        )

class CompanyInfoDisplay(View):

    template_name = "coaccounts/display_company_info.html"

    # send the user back to their own page after a successful update
    def get(self, request, *args, **kwargs):
        return render_to_response(
            self.template_name,
            {},
            context_instance=RequestContext(request)
        )

class CompanyInfoUpdate(View):


    template_name = "coaccounts/update_company_info.html"
    
    # send the user back to their own page after a successful update
    def get(self, request, *args, **kwargs):
        return render_to_response(
            self.template_name,
            {},
            context_instance=RequestContext(request)
        )

class LoadFixtures(View):
    template_name = "coaccounts/chart_of_account_visualization.html"

    def load_fixture(self):
        import datetime
        FiscalYear.objects.create(
            fiscal_year_from=datetime.datetime.now().date(),
            fiscal_year_to=datetime.datetime.now().date(),
        )
        primary_groups = [
            'Income',
            'Expenses',
            'Assets',
            'Liabilities'
            ]
        secondary_groups ={
        "Assets":[
            'Bank Accounts',
            'Bank OCC A/C',
            'Bank OD A/C',
            'Branch / Divisions',
            'Cash-in-hand',
            'Current Assets',
            'Fixed Assets',
            'Deposits (Asset)',
            'Investments',
            'Misc. Expenses (ASSET)',
            'Retained Earnings',
            'Reserves & Surplus',
            'Stock-in-hand',
        ],

        "Liabilities":[
            'Capital Account',
            'Current Liabilities',
            'Loans & Advances (Asset)',
            'Loans (Liability)',
            'Provisions',
            'Sundry Creditors',
            'Sundry Debtors',
            'Unsecured Loans',
            'Secured Loans',
        ],
        "Income":[

            'Direct Incomes',
            'Income (Direct)',
            'Indirect Incomes',
            'Income (Indirect)',
            'Export',   

            'Sales Accounts',
            ],
        "Expenses":[
            'Direct Expenses',
            'Duties & Taxes',
            'Expenses (Direct)',
            'Expenses (Indirect)',
            'Indirect Expenses',
            'Suspense A/C',
            'Purchase Accounts',
            ]
            }
        for primary_group in primary_groups:
            fiscal_year = FiscalYear.objects.all()[0]
            primary_object = AccountGroup(name=primary_group,parent = None,fiscal_year=fiscal_year)
            primary_object.save()
            for secondary_group in secondary_groups[primary_group]:
                secondary_object = AccountGroup(name=secondary_group,parent = primary_object, fiscal_year=fiscal_year)
                secondary_object.save() 



    def get(self,request,*args,**kwargs):
        if request.GET.get("q") == "load":
            self.load_fixture()

        return render_to_response(
            self.template_name,
            {},
            context_instance=RequestContext(request)
        )

erp_accounts/journal/views.py
from django.views.generic import CreateView, ListView, TemplateView
from django.core.urlresolvers import reverse

from .models import Journal


class JournalCreate(CreateView):
    model = Journal
    fields = ['description', ]


class JournalListView(ListView):
    model = Journal


class JournalUpdate(TemplateView):
    template_name = 'journal/journal_form.html'

    def get_context_data(self, **kwargs):
        # Call the base implementation first to get a context
        context = super(JournalUpdate, self).get_context_data(**kwargs)
        context['ajax_url'] = reverse('journal:journal-api', args=(kwargs.get('pk'), ))
        # Add in a QuerySet of all the books
        return context

erp_accounts/views.py
from django.views.generic import View
from django.shortcuts import render_to_response, HttpResponse
from django.template import RequestContext

class DashboardView(View):

    template_name = "accounts_dashboard.html"

    # send the user back to their own page after a successful update
    def get(self, request, *args, **kwargs):
        return render_to_response(
            self.template_name,
            {},
            context_instance=RequestContext(request)
        )

    # def get_object(self):
    #     # Only get the User record for the user making the request
    #     return User.objects.get(username=self.request.user.username)

erp_accounts/templates/journal/journal_form-old.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	
	<form action="">
		<div class="form-inline row">
			<div class="form-group">
				<label for="description">Description</label>
				<input name="description" class="form-control">
			</div>
		</div>
		<div class="form-inline row">
			<div class="form-group">
				<label for="Amount">Amount</label>
				<input type="decimal" name="amount" class="form-control">

				<label for="type">Type</label>
				<select name="type" class="form-control">
                    <option value="debit">Debit</option>
                    <option value="credit">Credit</option>
                </select>

                <label for="type">Ledger</label>
				<select name="type" class="form-control">
                    <option value="debit">NIBL</option>
                    <option value="credit">Everest</option>
                </select>
			</div>
		</div>

		<div class="form-inline row">
			<div class="form-group">
				<label for="Amount">Amount</label>
				<input type="decimal" name="amount" class="form-control">

				<label for="type">Type</label>
				<select name="type" class="form-control">
                    <option value="debit">Debit</option>
                    <option value="credit">Credit</option>
                </select>

                <label for="type">Ledger</label>
				<select name="type" class="form-control">
                    <option value="debit">NIBL</option>
                    <option value="credit">Everest</option>
                </select>


			</div>
		</div>
	</form>
	
{% endblock content %}

{% block javascript %}
	{{block.super}}
	<script src="{% static 'erp_accounts/journal/add-more-fields.js' %}"></script>
{%endblock javascript %}

erp_accounts/templates/journal/journal_form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block css %}
	<link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

	<link rel="stylesheet" type="text/css" href="{% static 'lib/bower_components/angular-progress-button-styles/dist/angular-progress-button-styles.min.css' %}">

	{{block.super}}

{% endblock %}

{% block content %}

{% verbatim %}
<div ng-app="journalApp">
	<div class="head-block">
		<h1>Journal Entry</h1>
	</div>

	<form name="newForm" ng-submit="submitForm()" ng-controller="JournalController">
		
		<div class="row form-group">
			<div class="col-sm-6">
				<div class="col-sm-12">
					<label for="journal_date">Date</label>
				</div>
				<div class="col-sm-12">
					<input type="date" name="journal_date" class="form-control" ng-model="journalForm.journal_date" ng-required required>
				</div>
				
			</div>
		</div>
		
		<transactions></transactions>
		<div class="row form-group">
			<div class="col-sm-6">
				<div class="col-sm-12">
					<label for="description">Description</label>
				</div>
				<div class="col-sm-12">
					<input name="description" class="form-control" ng-model="journalForm.description" ng-required="required">
				</div>
				
			</div>
		</div>

		<div class="row form-group">
			<div class="col-sm-4">
				<div class="col-sm-12">
					<button type="submit" ng-click=""   title="{{formError}}" id="submitBtn" ng-disabled="!formValid()" ng-class="{disabled: !formValid()}" data-horizontal pb-style="shrink" progress-button="submitForm()" style="max-height:60px">Submit</button>
				</div>
			</div>
		</div>
	<pre>{{ journalForm }}</pre>
	</form>

</div>
{% endverbatim %}
	
{% endblock content %}

{% block javascript %}
	{{block.super}}
	
	<!-- Angularjs -->
	
		<script src="{% static 'erp_accounts/journal/angular/app.js' %}">
		</script>
		<script src="{% static 'erp_accounts/journal/angular/services/JournalServices.js' %}">
		</script>
		<script src="{% static 'erp_accounts/journal/angular/controllers/JournalController.js' %}">
		</script>
		<script src="{% static 'erp_accounts/journal/angular/directives/JournalDirective.js' %}">
		</script>

		<script type="text/javascript" src="{% static 'lib/bower_components/angular-progress-button-styles/dist/angular-progress-button-styles.min.js' %}"></script>
		<script type="text/javascript" src="{% static 'lib/bower_components/angular-bootstrap-show-errors/src/showErrors.min.js' %}"></script>
	<!-- end angular -->

		<script>
			var globalVars = {};

			globalVars['ajax_url'] = "{% url 'journal:journal-list-create-api' %}";
			globalVars['method'] = 'POST';

			{% if ajax_url %}
				globalVars['ajax_url'] = "{{ajax_url}}";
				globalVars['method'] = 'PUT';
			{% endif %}
		</script>
{% endblock javascript %}

erp_accounts/templates/journal/journal_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block content %}
	<table border="1">
	<tr>
		<th>S.N.</th>
		<th>Date</th>
		<th>Description</th>
		<th>Debit</th>
		<th>Credit</th>
		<th></th>
	</tr>
	{% for journal in object_list %}
	<tr>
		<td>{{forloop.counter}}</td>
		<td>{{journal.journal_date}}</td>
		<td>{{journal.description}}</td>
		<td>
			{{journal.total_debit.amount}}
		</td>
		<td>
			{{journal.total_credit.amount}}
		</td>
		<td>
			<a class="btn btn-primary" href = "{% url 'journal:journal-update' journal.pk %}">Update</a>
		</td>
	</tr>
	
	{% endfor %}
	</table>
{% endblock content %}

erp_accounts/templates/journal/test.html
{% extends 'base.html' %}

{% block content %}
{% verbatim %}
<div ng-app="formExample">
  <div ng-controller="ExampleController">
  <form novalidate class="simple-form">
    Name: <input type="text" ng-model="user.name" /><br />
    E-mail: <input type="email" ng-model="user.email" /><br />
    Gender: <input type="radio" ng-model="user.gender" value="male" />male
    <input type="radio" ng-model="user.gender" value="female" />female<br />
    <input type="button" ng-click="reset()" value="Reset" />
    <input type="submit" ng-click="update(user)" value="Save" />
  </form>
  <pre>user = {{user | json}}</pre>
  <pre>master = {{master | json}}</pre>
</div>

<script>
  angular.module('formExample', [])
    .controller('ExampleController', ['$scope', function($scope) {
      $scope.master = {};

      $scope.update = function(user) {
        $scope.master = angular.copy(user);
      };

      $scope.reset = function() {
        $scope.user = angular.copy($scope.master);
      };

      $scope.reset();
    }]);
</script>
</div>
{% endverbatim %}
{% endblock %}